project:
  type: website
  output-dir: docs

format:
  html:
    theme: 
      light: yeti
      dark: superhero
    css: styles.css
    highlight-style: zenburn
    toc: false
    number-sections: false
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/cmu-sans-serif" type="text/css"/>
link-citations: true
mainfont: CMU Sans Serif

css: styles.css



website:
  title: "Roussel."
  # description: "Unapolagetically curious."
  site-url: https://ddrous.github.io/
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/ddrous
      - icon: envelope
        href: mailto:roussel.desmond.nzoyem@outlook.com
      - icon: rss
        href: index.xml
  page-footer:
    left: "Copyright © 2023 - Roussel Desmond Nzoyem"
    right: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
  # search: true
  # comments:
  #   giscus:
  #     repo: ddrous/ddrous.github.io
