project:
  type: website
  output-dir: docs

format:
  html:
    theme: 
      # For light mode: load cosmo, then common rules, then light-only rules
      light: [cosmo, custom.scss, styles_light.scss]
      # For dark mode: load superhero, then common rules, then dark-only rules
      dark: [superhero, custom.scss, styles_dark.scss]
    css:
      # This is correct - keep it as is
      - https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css
    highlight-style: zenburn
    toc: false
    number-sections: false
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&family=Inter:wght@400;600;700&display=swap" rel="stylesheet" media="print" onload="this.media='all'">
      <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    fig-width: 8
    fig-height: 6
    fig-dpi: 150
    minimal: true
    anchor-sections: false
    smooth-scroll: false
    code-tools: false
    code-fold: false
link-citations: true
mainfont: "Roboto Condensed"

website:
  title: "Roussel."
  site-url: https://ddrous.github.io/
  favicon: "assets/images/logo.png"
  open-graph: true
  google-analytics: "G-GLZPYK16BE"
  page-navigation: true
  reader-mode: true
  navbar:
    logo: "assets/images/logo.png"
    href: index.html
    left:
      - text: "About"
        href: "about.qmd"
      - text: "CV et al."
        href: "cv.qmd"
      - text: "Publications"
        href: "publications.qmd"
      - text: "Projects"
        href: "projects.qmd"
      - text: "Blog"
        href: "posts.qmd"
    right:
      - icon: github
        href: https://github.com/ddrous
      - icon: envelope
        href: mailto:rd.nzoyemngueguin@bristol.ac.uk
      - icon: rss
        href: index.xml
  page-footer:
    left: "Copyright © 2025 - Roussel Desmond Nzoyem"
    right: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    background: light