project:
  type: website

website:
  title: "Roussel."
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/ddrous
      - icon: linkedin
        href: https://www.linkedin.com/in/roussel-desmond-nzoyem/
format:
  html:
    theme: 
      light: yeti
      dark: superhero
    css: styles.css
    highlight-style: zenburn
    toc: false
    number-sections: false
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/cmu-sans-serif" type="text/css"/>
link-citations: true
mainfont: CMU Sans Serif



