project:
  type: website
  output-dir: docs

format:
  html:
    theme: 
      light: yeti
      dark: superhero
    css: styles.css
    highlight-style: zenburn
    toc: false
    number-sections: false
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/cmu-sans-serif" type="text/css"/>
link-citations: true
mainfont: CMU Sans Serif

# css: styles.css



website:
  title: "Roussel."
  # description: "Unapolagetically curious."
  site-url: https://ddrous.github.io/
  favicon: "assets/images/logo.png"
  open-graph: true
  google-analytics: "G-GLZPYK16BE"
  page-navigation: true
  # back-to-top-navigation: true
  reader-mode: true
  navbar:
    logo: "assets/images/logo.png"
    href: index.html
    left: 
      - about.qmd
      - projects.qmd
      # - text: "CV"
      #   href: "./cv/index.qmd"
      - cv.qmd
      - publications.qmd
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/ddrous
      - icon: envelope
        href: mailto:rd.nzoyemngueguin@bristol.ac.uk
      - icon: rss
        href: index.xml
  page-footer:
    left: "Copyright © 2023 - Roussel Desmond Nzoyem"
    right: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    background: light
  # sidebar:
    # style: "docked"
    # search: true
  # search: true
  # comments:
  #   giscus:
  #     repo: ddrous/ddrous.github.io
